### ISSUE TITLE
Waiting for the publicly available code

### ISSUE THREAD

**Issue by tahsirmunna** [FereshteShakeri/few-shot-MedVLMs#1]
**Dear Authors,**

You have done an excellent job with this work. In your paper,  you mentioned, _"We made our benchmark and code publicly available to trigger further developments in this emergent subject."_ However, we have yet to see the code released. We kindly hope it will be available soon.

Thank you.

**Comment by FereshteShakeri** [comment]
Hi, 
Thank you for your interest! Yes, we are finalizing the code and it will be available in the following week. :)
